version: '3.4'

services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    restart: unless-stopped
    depends_on:
      - bookify.db
    build:
      context: .
      dockerfile: Bookify.Api/Dockerfile
  
  bookify.db:
    image: postgres:latest
    container_name: Bookify.Db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
